services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    container_name: costs
    restart: always
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_content:/home/app/web/staticfiles
      - db-data:/home/app/web/db
    env_file:
      - ./.env.prod

networks:
  default:
    external:
      name: caddy_default

volumes:
  static_content:
  db-data: