services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    container_name: costs
    restart: always
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    networks:
      projectnet:
        ipv4_address: 172.26.0.2
    volumes:
      - static_content:/home/app/web/staticfiles
      - db-data:/home/app/web/db
    env_file:
      - ./.env.prod

networks:
  projectnet:
    external: true

volumes:
  static_content:
  db-data: