# Generated by Django 4.1 on 2023-03-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='currency',
            field=models.CharField(choices=[('RUB', 'Рубль'), ('USD', 'Доллар'), ('EUR', 'Евро'), ('TRY', 'Лира'), ('KZT', 'Тенге')], default='RUB', max_length=3),
        ),
    ]
